language: cpp
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env:
        - COMPILER=g++-4.7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
    - os: osx
      osx_image: xcode6.4
      compiler: g++
      env:
        - COMPILER=g++
 
    - os: osx
      osx_image: xcode7.3
      compiler: g++
      env:
        - COMPILER=g++
# refer: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
# for install a gcc on mac with OpenMP support
before_install:
  - uname -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then vm_stat; fi
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q && sudo apt-get install -y -qq gfortran; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gcc; brew reinstall gcc --without-multilib; fi
script: make CXX=$COMPILER -C third/ && make CXX=$COMPILER
